# Generated by Django 4.0.5 on 2022-06-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsfigures',
            name='pfig_location',
        ),
        migrations.RemoveField(
            model_name='projectsfiles',
            name='pfile_location',
        ),
    ]
